server:
  port: 9000

# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: ${spring.application.name}
  protocol:
    # 协议端口
    port: 20880
    # 协议名称
    name: ${spring.application.name}
  # 注册中心信息
  registry:
    address: zookeeper://127.0.0.1:2181
    # 默认组
    group: dubbo
  # 元数据中心
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  consumer:
    version: 1.0.0
    timeout: 30000
    # 检查是否有服务
    check: false
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.demofactory.template.service
