server:
  port: 9222
spring:
  application:
    # 应用名称
    name: 'template-service'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.184.142:3306/study1?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: study1
    password: study1

mybatis:
  mapper-locations:  'classpath:mapper/*Mapper.xml'
  type-aliases-package:  com.demofactory.template.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: ${spring.application.name}
  protocol:
    # 协议端口
    port: 20880
    # 协议名称
    name: ${spring.application.name}
  # 注册中心信息
  registry:
    address: zookeeper://127.0.0.1:2181
    # 默认组
    group: dubbo
  # 元数据中心
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  provider:
    protocol: dubbo
    version: 1.0.0
    timeout: 30000
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.demofactory.template.service

mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.demofactory.template.domain.enums
